# SPDX-License-Identifier: GPL-2.0
# DeepX Synopsys PCIe driver

ccflags-y += -I $(src)/include

ccflags-y += $(CCFLAGS)

ifneq ($(CONFIG_DX_AI_ACCEL_RT),)
ccflags-y += -DCONFIG_DX_AI_ACCEL_RT=1
ccflags-y += -I $(src)/../include
endif

ifeq ($(BUILD_DEFAULT_DBG), log)
ccflags-y += -DDX_DEBUG_ENABLE
else ifeq ($(BUILD_DEFAULT_DBG), perf)
ccflags-y += -DDX_DEBUG_FS
ccflags-y += -DDMA_PERF_MEASURE
else ifeq ($(BUILD_DEFAULT_DBG), debugfs)
ccflags-y += -DDX_DEBUG_FS
else ifeq ($(BUILD_DEFAULT_DBG), dump_desc)
ccflags-y += -DDUMP_DESC_TABLE
else ifeq ($(BUILD_DEFAULT_DBG), all)
ccflags-y += -DDX_DEBUG_ENABLE
ccflags-y += -DDX_DEBUG_FS
ccflags-y += -DDUMP_DESC_TABLE
ifneq ($(CONFIG_RPI_BUILD),)
ccflags-y += -DRPI_DEBUG_BUILD=1
endif
endif

ifneq ($(CONFIG_RPI_BUILD),)
ccflags-y += -DRPI_BUILD=1
endif

dx_dma-y := dw-edma-pcie.o dw-edma-core.o dw-edma-v0-core.o \
		dw-edma-v0-debugfs.o dw-edma-thread.o dx_util.o \
		dx_cdev.o dx_sgdma_cdev.o dx_cdev_ctrl.o \
		dx_cdev_events.o dx_sgdma.o 

ifneq ($(filter -DRPI_DEBUG_BUILD=1,$(ccflags-y)),)
ccflags-y += -I $(src)/utils/rpi
endif

ifneq ($(CONFIG_DX_AI_ACCEL_RT),)
dx_dma-y += dx_message.o
endif

ifeq ($(CONFIG_DMA_VIRTUAL_CHANNELS),)
dx_dma-y += virt-dma.o
endif

obj-$(CONFIG_DX_AI_ACCEL_PCIE_DEEPX) += dx_dma.o
