# SPDX-License-Identifier: GPL-2.0
#  DeepX AI accelerators RT driver

ccflags-y += -I $(src)/../include

ifeq ($(CONFIG_DX_AI_ACCEL_M1),y)
ccflags-y += -DIS_ACCELERATOR=1
ccflags-y += -DIS_STANDALONE=0
ccflags-y += -DDEVICE_TYPE=0
ccflags-y += -DDEVICE_VARIANT=DX_M1
else ifeq ($(CONFIG_DX_AI_ACCEL_L1),y)
ccflags-y += -DIS_ACCELERATOR=0
ccflags-y += -DIS_STANDALONE=1
ccflags-y += -DDEVICE_TYPE=1
ccflags-y += -DDEVICE_VARIANT=DX_L1
ccflags-y += -DNUM_DEVICES=1
else ifeq ($(CONFIG_DX_AI_ACCEL_L3),y)
ccflags-y += -DIS_ACCELERATOR=0
ccflags-y += -DIS_STANDALONE=1
ccflags-y += -DDEVICE_TYPE=1
ccflags-y += -DDEVICE_VARIANT=DX_L3
ccflags-y += -DNUM_DEVICES=1
else
$(error Error: No selected device)
endif

ifeq ($(CONFIG_DX_AI_ACCEL_PCIE_XILINX),m)
ccflags-y += -DNUM_DEVICES=1 # temp for alveo fpga
else
ccflags-y += -DNUM_DEVICES=0
endif

ifeq ($(filter log all,$(BUILD_DEFAULT_DBG)),log all)
ccflags-y += -DDEBUG
endif

dxrt_driver-y := dxrt_drv.o dxrt_drv_cdev.o dxrt_drv_npu.o \
		dxrt_drv_message.o dxrt_drv_queue.o dxrt_drv_thread.o

dxrt_driver-$(CONFIG_DX_AI_ACCEL_L1) += dxrt_drv_npu_l1.o
dxrt_driver-$(CONFIG_DX_AI_ACCEL_L3) += dxrt_drv_npu_l3.o

obj-$(CONFIG_DX_AI_ACCEL_RT) += dxrt_driver.o
