name: main

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions: write-all

jobs:
    release:
        name: checkout
        if: github.repository == 'DEEPX-AI/dx_rt_npu_linux_driver'
        runs-on: self-hosted
        timeout-minutes: 5
        steps:
            - name: Clean
              run: |
                  sudo rm -rf ${{ github.workspace }}
                  mkdir -p ${{ github.workspace }}
            
            - name: Checkout 
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true
                token: ${{ secrets.GH_TOKEN }}
            
            - name: Create tag
              uses: rickstaa/action-create-tag@v1
              with:
                  tag_exists_error: false
                  tag: ${{ github.event.head_commit.message }}
                  force_push_tag: true
                  commit_sha: ${{ github.event.head_commit.ref}}
                  message: '${{ github.event.head_commit.message }}'

            - name: Create Release
              uses: ghalactic/github-release-from-tag@v5
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  draft: "false"
                  prerelease: "false"
                  summaryEnabled: "true"